-- ============================================
-- GAME 3: LIGHTS OUT — RESCUE THE CITY
-- Replaces Kingdom Builders as the live-event finale.
-- ============================================

UPDATE game_questions
SET is_active = FALSE
WHERE game_key = 'kingdom_builders';

DELETE FROM game_questions WHERE game_key = 'lights_out';

INSERT INTO game_questions (game_key, sequence, question_text, question_type, options, correct_option, explanation, bible_reference, source_label, time_limit_seconds, difficulty, is_active) VALUES
('lights_out', 1,
'Your friend sends a screenshot mocking another student. The group chat is laughing. What is the best Light Move?',
'multiple_choice',
'["Tell the group to stop, refuse to share it, and check on the student privately","Forward it so more people can see it","Stay silent and pretend you did not see it","Edit the screenshot into a meme so it feels less serious"]'::jsonb,
0,
'Light restores dignity. Being light online means refusing cruelty, protecting people, and using your voice with courage.',
'Ephesians 4:29',
'Online Life',
25,
'medium',
TRUE),
('lights_out', 2,
'You used AI to explain your homework. The answer sounds confident, but you are not fully sure it is correct. What is the best Light Move?',
'multiple_choice',
'["Copy it immediately because AI sounds smart","Check it with your textbook, class notes, or teacher before using it","Tell your friends AI is always more accurate than people","Change a few words so nobody knows you used AI"]'::jsonb,
1,
'Use AI to learn faster, but wisdom verifies before trusting. Confidence is not the same as truth.',
'1 Thessalonians 5:21',
'School',
25,
'hard',
TRUE),
('lights_out', 3,
'A link says you won free data if you enter your password and phone number. What is the best Light Move?',
'multiple_choice',
'["Enter quickly before the offer expires","Share it with the church group so everyone can win","Ignore the link, do not enter details, and ask a trusted adult to verify it","Use your friend’s phone number instead"]'::jsonb,
2,
'Light includes wisdom and protection. Your private information is not something to trade for pressure or fake rewards.',
'Proverbs 22:3',
'Digital Safety',
25,
'easy',
TRUE),
('lights_out', 4,
'You notice a new student sitting alone at youth conference. Your friends want to keep your normal circle closed. What is the best Light Move?',
'multiple_choice',
'["Wait for a leader to handle it","Laugh about how awkward they look","Ignore them so your friends do not tease you","Invite them in and help them feel seen"]'::jsonb,
3,
'Jesus calls us to love people practically. Light makes room for others instead of leaving them invisible.',
'Luke 10:33-37',
'Church',
25,
'medium',
TRUE),
('lights_out', 5,
'You are angry and about to post something that will embarrass someone publicly. What is the best Light Move?',
'multiple_choice',
'["Save it, pray, cool down, and choose a private respectful conversation if needed","Post it now before you calm down","Ask followers to vote if you should expose them","Use AI to write a harsher caption"]'::jsonb,
0,
'Technology is powerful; character must lead. Self-control protects people and protects your witness.',
'Proverbs 15:1',
'Online Life',
25,
'easy',
TRUE),
('lights_out', 6,
'Your classmate asks you to send answers during a test because “everyone cheats small.” What is the best Light Move?',
'multiple_choice',
'["Send the answers to keep the friendship","Refuse kindly, stay honest, and offer to help them study later","Send wrong answers as a joke","Use AI during the test and split the marks"]'::jsonb,
1,
'Light is integrity when pressure is high. Helping someone prepare is love; helping them cheat is not.',
'Proverbs 10:9',
'School',
25,
'easy',
TRUE),
('lights_out', 7,
'An AI chatbot gives you spiritual advice that contradicts a Bible verse you know. What is the best Light Move?',
'multiple_choice',
'["Trust the chatbot because it knows everything","Post it as a Bible verse because it sounds deep","Compare it with Scripture and ask a mature Christian leader for guidance","Keep asking until AI agrees with you"]'::jsonb,
2,
'AI is a tool, not spiritual authority. Scripture, prayer, wise counsel, and responsibility come first.',
'2 Timothy 3:16-17',
'Faith + AI',
25,
'hard',
TRUE),
('lights_out', 8,
'You have a talent for design, music, coding, drama, or speaking, but you feel it is not spiritual enough. What is the best Light Move?',
'multiple_choice',
'["Hide the gift because only preaching matters","Only use it if it makes you famous","Compare yourself until you quit","Use the gift to serve people, build others up, and glorify God"]'::jsonb,
3,
'Your gifts can solve real problems and serve people. Light shines when gifts become service, not just attention.',
'1 Peter 4:10',
'Purpose',
25,
'easy',
TRUE),
('lights_out', 9,
'A viral video claims a Bible verse says something shocking, but no reference is shown. What is the best Light Move?',
'multiple_choice',
'["Look up the reference, compare translations, and verify before sharing","Believe it because it is emotional","Share it with “wow” before checking","Argue in the comments without checking"]'::jsonb,
0,
'Truth is worth checking. Not everything that sounds wise, religious, emotional, or convincing is true.',
'Acts 17:11',
'Truth Check',
25,
'easy',
TRUE),
('lights_out', 10,
'Your younger sibling wants help with homework. You are busy scrolling and annoyed. What is the best Light Move?',
'multiple_choice',
'["Tell them to stop disturbing you","Help for a short focused time, then return to your work","Give them AI answers without explaining","Mock them for not understanding"]'::jsonb,
1,
'Light starts at home. Serving does not always look dramatic; sometimes it looks like patient help.',
'Galatians 5:13',
'Home',
25,
'medium',
TRUE),
('lights_out', 11,
'Your friend confesses they are struggling with anxiety and cannot pray. What is the best Light Move?',
'multiple_choice',
'["Tell them real Christians never feel anxious","Post their story as anonymous content","Listen, encourage them, pray with them if they want, and help them speak to a trusted adult/leader","Send one motivational quote and disappear"]'::jsonb,
2,
'Being light means compassion and responsibility. Listen well, pray, and help people reach safe support.',
'Romans 12:15',
'Friendship',
25,
'easy',
TRUE),
('lights_out', 12,
'You want to use AI to make church content for teenagers. What is the best Light Move?',
'multiple_choice',
'["Let AI invent Bible verses so the posts sound powerful","Copy trending content even if it is false","Use fear and shame because it gets more views","Use AI for ideas and drafts, then verify Scripture, edit with care, and label examples clearly"]'::jsonb,
3,
'Use AI to create and serve, but never fake Scripture or replace truth with hype.',
'Colossians 3:17',
'Church',
25,
'hard',
TRUE),
('lights_out', 13,
'Someone asks for your location, school name, and private photos in a game chat. What is the best Light Move?',
'multiple_choice',
'["Refuse, block/report if needed, and tell a trusted adult","Send it if they seem nice","Send old photos so it is safer","Keep chatting but hide it from your parents"]'::jsonb,
0,
'Digital safety is wisdom. Do not give strangers private access to your life.',
'Proverbs 4:23',
'Digital Safety',
25,
'medium',
TRUE),
('lights_out', 14,
'Your group is planning a school clean-up, but people say it is not cool. What is the best Light Move?',
'multiple_choice',
'["Quit so nobody laughs","Serve anyway and invite others with a clear, positive plan","Complain online but do nothing","Only join if someone records you"]'::jsonb,
1,
'Light changes environments through action. Good works point beyond you to God.',
'Matthew 5:16',
'Community',
25,
'easy',
TRUE),
('lights_out', 15,
'You discover an embarrassing rumor about someone is false. People are still spreading it. What is the best Light Move?',
'multiple_choice',
'["Stay quiet because drama is entertaining","Add your own version so it sounds funnier","Help stop the rumor, speak truth carefully, and protect the person from more shame","Use AI to generate more gossip"]'::jsonb,
2,
'Light exposes lies without destroying people. Truth and love must work together.',
'Ephesians 4:15',
'Truth Check',
25,
'easy',
TRUE),
('lights_out', 16,
'You are exhausted from trying to impress everyone online. What is the best Light Move?',
'multiple_choice',
'["Post more so nobody forgets you","Compare yourself until you improve","Create a fake perfect version of your life","Take a healthy break, remember your identity in Christ, and use tech with boundaries"]'::jsonb,
3,
'You are not your likes, views, or streaks. Character and identity are deeper than performance.',
'Romans 12:2',
'Identity',
25,
'medium',
TRUE),
('lights_out', 17,
'A friend wants to use AI to generate an apology instead of actually taking responsibility. What is the best Light Move?',
'multiple_choice',
'["Use AI only to organize thoughts, then personally own the wrong and speak honestly","Let AI apologize and move on","Deny everything","Make the apology sound spiritual but avoid changing"]'::jsonb,
0,
'AI can help words, but it cannot replace repentance, humility, and changed behavior.',
'James 5:16',
'Character',
25,
'hard',
TRUE),
('lights_out', 18,
'Your team has one minute to encourage the hall before the final score. What is the best Light Move?',
'multiple_choice',
'["Brag about being smarter than everyone","Celebrate others, point to the theme, and challenge everyone to shine this week","Mock the lowest scores","Say nothing because only winners matter"]'::jsonb,
1,
'No one should be shamed. The real win is leaving ready to shine at school, church, home, and online.',
'Matthew 5:14-16',
'Finale',
25,
'easy',
TRUE);

SELECT game_key, COUNT(*) AS question_count
FROM game_questions
WHERE game_key IN ('kingdom_builders', 'lights_out')
GROUP BY game_key
ORDER BY game_key;
